const footballTeams = [
  {
    id: '65c1fe6be3d6499b5031b39e',
    teamLogo: '../../assets/images/teamLogo/Chelsea.svg',
    teamName: 'Chelsea',
    teamFullName: 'Chelsea Football Club',
    nickName: 'The Blues',
    founded: '1905',
    ground: 'Stamford Bridge',
    league: 'Premier League',
    aboutTeam: `Chelsea Football Club, founded in 1905, has evolved into one of England's most successful football institutions. The club's modern era of success began after Roman Abramovich's acquisition in 2003, transforming them into a European powerhouse. They secured their first UEFA Champions League trophy in 2012, followed by another in 2021, alongside multiple Premier League titles and domestic cups.

    The club's commitment to youth development through their academy has produced numerous talented players, while their strategic recruitment has attracted some of football's biggest stars. Chelsea's playing style has adapted under different managers, but they've maintained a reputation for strong defensive organization combined with attacking flair, making them one of the most tactically versatile teams in European football.`,
    players: [
      'Robert Sánchez #1',
      'Marc Cucurella #3',
      'Thiago Silva #6',
      'Raheem Sterling #7',
      'Enzo Fernández #8',
      'Cole Palmer #10',
      'Nicolas Jackson #15',
      'Conor Gallagher #20',
      'Carney Chukwuemeka #23',
      'Christopher Nkunku #26',
      'Mykhailo Mudryk #28',
    ],
    gallery: [
      '../../assets/images/teamImages/Chelsea/Chelsea1.jpg',
      '../../assets/images/teamImages/Chelsea/Chelsea2.jpg',
      '../../assets/images/teamImages/Chelsea/Chelsea3.jpg',
      '../../assets/images/teamImages/Chelsea/Chelsea4.jpg',
    ],
    teamFormation: '../../assets/images/teamFormation/ChelseaForm.jpg',
  },
  {
    id: '65c2120026908c0b6257c183',
    teamLogo: '../../assets/images/teamLogo/bayernMunich.svg',
    teamName: 'Bayern Munich',
    teamFullName: 'Fußball-Club Bayern München e.V.',
    nickName: 'The Bavarians',
    founded: '1900',
    ground: 'Allianz Arena',
    league: 'Bundesliga',
    aboutTeam: `Bayern Munich stands as Germany's most successful football club and one of Europe's most prestigious institutions. Founded in 1900, the club has dominated German football, winning an unprecedented number of Bundesliga titles and establishing itself as a constant presence in European competitions, with multiple UEFA Champions League victories to their name, including their historic treble-winning seasons.

    The club's philosophy of combining homegrown talent with world-class signings has created a sustainable model of success. Their recruitment strategy focuses on acquiring both established stars and promising young talents, while their youth academy, known as the FC Bayern Campus, continues to produce exceptional players who seamlessly integrate into the first team, maintaining a strong German core while competing at the highest international level.`,
    players: [
      'Manuel Neuer #1',
      'Matthijs de Ligt #4',
      'Joshua Kimmich #6',
      'Harry Kane #7',
      'Leon Goretzka #8',
      'Leroy Sané #10',
      'Kingsley Coman #11',
      'Thomas Müller #14',
      'Raphaël Guerreiro #21',
      'Jamal Musiala #27',
      'Kim Min-jae #3',
    ],
    gallery: [
      '../../assets/images/teamImages/bayernMunich/bayernMunich1.jpg',
      '../../assets/images/teamImages/bayernMunich/bayernMunich2.webp',
      '../../assets/images/teamImages/bayernMunich/bayernMunich3.jpg',
      '../../assets/images/teamImages/bayernMunich/bayernMunich4.webp',
    ],
    teamFormation: '../../assets/images/teamFormation/ByrenForm.jpg',
  },
  {
    id: '65c2138b26908c0b6257c18b',
    teamLogo: '../../assets/images/teamLogo/FcBarcelona.svg',
    teamName: 'Barcelona',
    teamFullName: 'Futbol Club Barcelona',
    nickName: 'Blaugrana',
    founded: '1899',
    ground: 'Spotify Camp Nou',
    league: 'La Liga',
    aboutTeam: `FC Barcelona, founded in 1899, represents more than just a football club, as reflected in their motto "Més que un club" (More than a club). The club has been at the forefront of Spanish and European football, winning numerous La Liga titles and Champions League trophies. Their commitment to attacking football and possession-based play, epitomized during the Pep Guardiola era, has influenced football philosophy worldwide.

    La Masia, Barcelona's renowned youth academy, has produced some of football's greatest talents, including Lionel Messi, Xavi, and Andrés Iniesta. This commitment to youth development and playing attractive football has become synonymous with the Barcelona brand, creating a distinctive style known as "tiki-taka" that has been admired and emulated globally.`,
    players: [
      'Marc-André ter Stegen #1',
      'João Cancelo #2',
      'Ronald Araújo #4',
      'Pedri #8',
      'Robert Lewandowski #9',
      'Raphinha #11',
      'João Félix #14',
      'Frenkie de Jong #21',
      'Jules Koundé #23',
      'Gavi #6',
      'Lamine Yamal #27',
    ],
    gallery: [
      '../../assets/images/teamImages/FcBarcelona/FcBarcelona1.jpg',
      '../../assets/images/teamImages/FcBarcelona/FcBarcelona2.jpg',
      '../../assets/images/teamImages/FcBarcelona/FcBarcelona3.jpg',
      '../../assets/images/teamImages/FcBarcelona/FcBarcelona4.jpg',
    ],
    teamFormation: '../../assets/images/teamFormation/BarcelonaForm.jpg',
  },
  {
    id: '65c2151d26908c0b6257c19c',
    teamLogo: '../../assets/images/teamLogo/juventus.svg',
    teamName: 'Juventus',
    teamFullName: 'Juventus Football Club',
    nickName: 'The Old Lady',
    founded: '1897',
    ground: 'Allianz Stadium',
    league: 'Serie A',
    aboutTeam: `Juventus Football Club, founded in 1897, stands as Italy's most successful football institution and one of the world's most renowned clubs. With a record number of Serie A titles and numerous domestic cups, they have dominated Italian football for generations. Their success extends to European competitions, with multiple UEFA Champions League finals appearances and victories.

    The club's philosophy of "winning is not important, it's the only thing that matters" has shaped their competitive mentality. This winning tradition has attracted some of football's greatest players throughout history, from Michel Platini and Zinedine Zidane to Cristiano Ronaldo, making them one of the most prestigious destinations for world-class talent.`,
    players: [
      'Wojciech Szczęsny #1',
      'Bremer #3',
      'Manuel Locatelli #5',
      'Dusan Vlahovic #9',
      'Federico Chiesa #7',
      'Adrien Rabiot #25',
      'Weston McKennie #16',
      'Danilo #6',
      'Federico Gatti #4',
      'Andrea Cambiaso #27',
      'Kenan Yildiz #15',
    ],
    gallery: [
      '../../assets/images/teamImages/juventus/juventus1.webp',
      '../../assets/images/teamImages/juventus/juventus2.webp',
      '../../assets/images/teamImages/juventus/juventus3.jpg',
      '../../assets/images/teamImages/juventus/juventus4.avif',
    ],
    teamFormation: '../../assets/images/teamFormation/ManchesterForm.jpg',
  },
  {
    id: '65c2166226908c0b6257c1a3',
    teamLogo: '../../assets/images/teamLogo/manchesterUnited.svg',
    teamName: 'Manchester United',
    teamFullName: 'Manchester United Football Club',
    nickName: 'The Red Devils',
    founded: '1878',
    ground: 'Old Trafford',
    league: 'Premier League',
    aboutTeam: `Manchester United, established in 1878 as Newton Heath LYR Football Club, has grown into one of the most successful and widely supported football clubs in the world. The club's rich history includes periods of triumph and tragedy, most notably the Munich Air Disaster of 1958, which helped forge the club's resilient character and determination to honor those lost by achieving greatness.

    Under Sir Alex Ferguson's 26-year reign (1986-2013), the club experienced unprecedented success, winning 13 Premier League titles and two UEFA Champions League trophies among numerous other honors. This period established United as a global footballing powerhouse and helped create one of the sport's most valuable brands, with a worldwide fanbase numbering in the hundreds of millions.`,
    players: [
      'André Onana #24',
      'Aaron Wan-Bissaka #29',
      'Harry Maguire #5',
      'Lisandro Martínez #6',
      'Bruno Fernandes #8',
      'Marcus Rashford #10',
      'Rasmus Højlund #11',
      'Christian Eriksen #14',
      'Casemiro #18',
      'Antony #21',
      'Luke Shaw #23',
    ],
    gallery: [
      '../../assets/images/teamImages/manchesterUnited/manchesterUnited1.jpg',
      '../../assets/images/teamImages/manchesterUnited/manchesterUnited2.jpg',
      '../../assets/images/teamImages/manchesterUnited/manchesterUnited3.avif',
      '../../assets/images/teamImages/manchesterUnited/manchesterUnited4.png',
    ],
    teamFormation: '../../assets/images/teamFormation/ManchesterForm.jpg',
  },
  {
    id: '65c2186326908c0b6257c1aa',
    teamLogo: '../../assets/images/teamLogo/realMadrid.svg',
    teamName: 'Real Madrid',
    teamFullName: 'Real Madrid Club de Fútbol',
    nickName: 'Los Blancos',
    founded: '1902',
    ground: 'Santiago Bernabéu Stadium',
    league: 'La Liga',
    aboutTeam: `Real Madrid Club de Fútbol, founded in 1902, stands as the most successful club in European football history. With a record number of UEFA Champions League/European Cup titles and numerous domestic honors, they have set the standard for excellence in club football. Their status as FIFA's Club of the 20th Century reflects their immense impact on the sport's development and global popularity.

    The club's philosophy of signing "Galácticos" - the world's most prestigious and talented players - has helped create some of football's most memorable teams. From Alfredo Di Stéfano and Ferenc Puskás to Cristiano Ronaldo and Karim Benzema, Real Madrid has consistently featured the game's greatest talents, contributing to their reputation for spectacular, attacking football.`,
    players: [
      'Thibaut Courtois #1',
      'Dani Carvajal #2',
      'Éder Militão #3',
      'David Alaba #4',
      'Jude Bellingham #5',
      'Luka Modrić #10',
      'Rodrygo #11',
      'Vinícius Júnior #7',
      'Toni Kroos #8',
      'Eduardo Camavinga #12',
      'Federico Valverde #15',
    ],
    gallery: [
      '../../assets/images/teamImages/realMadrid/realMadrid1.webp',
      '../../assets/images/teamImages/realMadrid/realMadrid2.jpg',
      '../../assets/images/teamImages/realMadrid/realMadrid3.jpg',
      '../../assets/images/teamImages/realMadrid/realMadrid4.jpg',
    ],
    teamFormation: '../../assets/images/teamFormation/RealForm.jpg',
  },
];

export default footballTeams;
